// Code generated by Serv compiler. DO NOT EDIT.
package main

import (
	"time"
	"strings"
	"fmt"
	"serv/runtime"
)

var _ = fmt.Sprintf
var _ = runtime.Noop
var _ = time.Second
var _ = strings.Join


// isTruthy evaluates truthiness of an interface{} value.
func isTruthy(v interface{}) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case int64:
		return val != 0
	case float64:
		return val != 0
	case string:
		return val != ""
	default:
		return true
	}
}

// toSlice coerces an interface{} to []interface{} for range iteration.
func toSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	if s, ok := v.([]interface{}); ok {
		return s
	}
	return nil
}

// multiReturn splits a value into (result, error) for multi-return assignment.
// If the value is a [2]interface{} tuple, it unpacks it.
// If the value is an error, returns (nil, error).
// Otherwise returns (value, nil).
func multiReturn(v interface{}) (interface{}, interface{}) {
	if v == nil {
		return nil, nil
	}
	if tuple, ok := v.([2]interface{}); ok {
		return tuple[0], tuple[1]
	}
	if err, ok := v.(error); ok {
		return nil, err.Error()
	}
	return v, nil
}

// safeCall executes a function and catches any panic, returning (result, error).
// Used by multi-return let statements: let val, err = expr
func safeCall(fn func() interface{}) (interface{}, interface{}) {
	var result interface{}
	var errVal interface{}
	func() {
		defer func() {
			if r := recover(); r != nil {
				errVal = fmt.Sprint(r)
			}
		}()
		result = fn()
	}()
	// If the result is already a tuple (from safe runtime functions), unpack it
	if tuple, ok := result.([2]interface{}); ok {
		return tuple[0], tuple[1]
	}
	return result, errVal
}

// toInt converts an interface{} to int
func toInt(v interface{}) int {
	switch val := v.(type) {
	case int:
		return val
	case float64:
		return int(val)
	case int64:
		return int(val)
	default:
		return 0
	}
}

// toFloat64 converts an interface{} to float64
func toFloat64(v interface{}) float64 {
	switch val := v.(type) {
	case float64:
		return val
	case int:
		return float64(val)
	case int64:
		return float64(val)
	default:
		return 0.0
	}
}

// toBool converts an interface{} to bool
func toBool(v interface{}) bool {
	if val, ok := v.(bool); ok {
		return val
	}
	return isTruthy(v)
}

// toString converts an interface{} to string
func toString(v interface{}) string {
	if v == nil {
		return ""
	}
	if val, ok := v.(string); ok {
		return val
	}
	return fmt.Sprint(v)
}

func main() {
	runtime.StartServer()
}
