name: Auto Release Tagger

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(grep -m 1 -oP '(?<=## \[)\d+\.\d+\.\d+' CHANGELOG.md)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${process.env.VERSION}`,
              sha: context.sha
            })
